// Package mocks centralizes test doubles for the application's interfaces.
//
// Naming convention: `Mock<Interface>` types are generated by go:generate with
// gomock; any other type (such as ConfigClient) is a hand-written fake for a
// stateful behavior that gomock mocks don't model well.
//
// Regenerate with `go generate ./internal/mocks/` (or `make gen-mock`).
package mocks

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination report.go -package mocks github.com/fikrimohammad/efficient-report-exporter/usecase Report
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination repository.go -package mocks github.com/fikrimohammad/efficient-report-exporter/repository MySQL,MQ,Redis,S3
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination sdk_db.go -package mocks github.com/fikrimohammad/go-dev-sdk/db DB
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination sdk_redis.go -package mocks -mock_names Client=MockRedisClient,Pipeline=MockRedisPipeline github.com/fikrimohammad/go-dev-sdk/redis Client,Pipeline
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination sdk_s3.go -package mocks -mock_names Client=MockS3Client github.com/fikrimohammad/go-dev-sdk/s3 Client
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination sdk_rocketmq.go -package mocks -mock_names Client=MockProducerClient github.com/fikrimohammad/go-dev-sdk/rocketmq/producer Client
