// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fikrimohammad/efficient-report-exporter/usecase (interfaces: Report)
//
// Generated by this command:
//
//	mockgen -destination report.go -package mocks github.com/fikrimohammad/efficient-report-exporter/usecase Report
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/fikrimohammad/efficient-report-exporter/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockReport is a mock of Report interface.
type MockReport struct {
	ctrl     *gomock.Controller
	recorder *MockReportMockRecorder
	isgomock struct{}
}

// MockReportMockRecorder is the mock recorder for MockReport.
type MockReportMockRecorder struct {
	mock *MockReport
}

// NewMockReport creates a new mock instance.
func NewMockReport(ctrl *gomock.Controller) *MockReport {
	mock := &MockReport{ctrl: ctrl}
	mock.recorder = &MockReportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReport) EXPECT() *MockReportMockRecorder {
	return m.recorder
}

// GetExportReportJob mocks base method.
func (m *MockReport) GetExportReportJob(ctx context.Context, params usecase.GetExportReportJobParams) (*usecase.GetExportReportJobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportReportJob", ctx, params)
	ret0, _ := ret[0].(*usecase.GetExportReportJobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportReportJob indicates an expected call of GetExportReportJob.
func (mr *MockReportMockRecorder) GetExportReportJob(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportReportJob", reflect.TypeOf((*MockReport)(nil).GetExportReportJob), ctx, params)
}

// ListExportReportJobs mocks base method.
func (m *MockReport) ListExportReportJobs(ctx context.Context, params usecase.ListExportReportJobsParams) (*usecase.ListExportReportJobsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExportReportJobs", ctx, params)
	ret0, _ := ret[0].(*usecase.ListExportReportJobsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExportReportJobs indicates an expected call of ListExportReportJobs.
func (mr *MockReportMockRecorder) ListExportReportJobs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExportReportJobs", reflect.TypeOf((*MockReport)(nil).ListExportReportJobs), ctx, params)
}

// ProcessExportReport mocks base method.
func (m *MockReport) ProcessExportReport(ctx context.Context, params usecase.ProcessExportReportParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessExportReport", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessExportReport indicates an expected call of ProcessExportReport.
func (mr *MockReportMockRecorder) ProcessExportReport(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessExportReport", reflect.TypeOf((*MockReport)(nil).ProcessExportReport), ctx, params)
}

// RequestExportReport mocks base method.
func (m *MockReport) RequestExportReport(ctx context.Context, params usecase.RequestExportReportParams) (*usecase.RequestExportReportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestExportReport", ctx, params)
	ret0, _ := ret[0].(*usecase.RequestExportReportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestExportReport indicates an expected call of RequestExportReport.
func (mr *MockReportMockRecorder) RequestExportReport(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestExportReport", reflect.TypeOf((*MockReport)(nil).RequestExportReport), ctx, params)
}
