// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fikrimohammad/efficient-report-exporter/repository (interfaces: MySQL,MQ,Redis,S3)
//
// Generated by this command:
//
//	mockgen -destination repository.go -package mocks github.com/fikrimohammad/efficient-report-exporter/repository MySQL,MQ,Redis,S3
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/fikrimohammad/efficient-report-exporter/model"
	repository "github.com/fikrimohammad/efficient-report-exporter/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockMySQL is a mock of MySQL interface.
type MockMySQL struct {
	ctrl     *gomock.Controller
	recorder *MockMySQLMockRecorder
	isgomock struct{}
}

// MockMySQLMockRecorder is the mock recorder for MockMySQL.
type MockMySQLMockRecorder struct {
	mock *MockMySQL
}

// NewMockMySQL creates a new mock instance.
func NewMockMySQL(ctrl *gomock.Controller) *MockMySQL {
	mock := &MockMySQL{ctrl: ctrl}
	mock.recorder = &MockMySQLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMySQL) EXPECT() *MockMySQLMockRecorder {
	return m.recorder
}

// CountReport mocks base method.
func (m *MockMySQL) CountReport(ctx context.Context, filter repository.QueryReportFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReport", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReport indicates an expected call of CountReport.
func (mr *MockMySQLMockRecorder) CountReport(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReport", reflect.TypeOf((*MockMySQL)(nil).CountReport), ctx, filter)
}

// InsertExportReportJob mocks base method.
func (m *MockMySQL) InsertExportReportJob(ctx context.Context, params repository.InsertExportReportJobParams) (*model.ExportReportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertExportReportJob", ctx, params)
	ret0, _ := ret[0].(*model.ExportReportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertExportReportJob indicates an expected call of InsertExportReportJob.
func (mr *MockMySQLMockRecorder) InsertExportReportJob(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertExportReportJob", reflect.TypeOf((*MockMySQL)(nil).InsertExportReportJob), ctx, params)
}

// QueryExportReportJob mocks base method.
func (m *MockMySQL) QueryExportReportJob(ctx context.Context, params repository.QueryExportReportJobFilter) ([]*model.ExportReportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExportReportJob", ctx, params)
	ret0, _ := ret[0].([]*model.ExportReportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExportReportJob indicates an expected call of QueryExportReportJob.
func (mr *MockMySQLMockRecorder) QueryExportReportJob(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExportReportJob", reflect.TypeOf((*MockMySQL)(nil).QueryExportReportJob), ctx, params)
}

// QueryReport mocks base method.
func (m *MockMySQL) QueryReport(ctx context.Context, filter repository.QueryReportFilter) ([]*model.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryReport", ctx, filter)
	ret0, _ := ret[0].([]*model.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryReport indicates an expected call of QueryReport.
func (mr *MockMySQLMockRecorder) QueryReport(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryReport", reflect.TypeOf((*MockMySQL)(nil).QueryReport), ctx, filter)
}

// UpdateExportReportJob mocks base method.
func (m *MockMySQL) UpdateExportReportJob(ctx context.Context, params repository.UpdateExportReportJobParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExportReportJob", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExportReportJob indicates an expected call of UpdateExportReportJob.
func (mr *MockMySQLMockRecorder) UpdateExportReportJob(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExportReportJob", reflect.TypeOf((*MockMySQL)(nil).UpdateExportReportJob), ctx, params)
}

// MockMQ is a mock of MQ interface.
type MockMQ struct {
	ctrl     *gomock.Controller
	recorder *MockMQMockRecorder
	isgomock struct{}
}

// MockMQMockRecorder is the mock recorder for MockMQ.
type MockMQMockRecorder struct {
	mock *MockMQ
}

// NewMockMQ creates a new mock instance.
func NewMockMQ(ctrl *gomock.Controller) *MockMQ {
	mock := &MockMQ{ctrl: ctrl}
	mock.recorder = &MockMQMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMQ) EXPECT() *MockMQMockRecorder {
	return m.recorder
}

// PublishExportReportDoneMsg mocks base method.
func (m *MockMQ) PublishExportReportDoneMsg(ctx context.Context, params model.ExportReportDoneMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishExportReportDoneMsg", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishExportReportDoneMsg indicates an expected call of PublishExportReportDoneMsg.
func (mr *MockMQMockRecorder) PublishExportReportDoneMsg(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishExportReportDoneMsg", reflect.TypeOf((*MockMQ)(nil).PublishExportReportDoneMsg), ctx, params)
}

// PublishExportReportProcessMsg mocks base method.
func (m *MockMQ) PublishExportReportProcessMsg(ctx context.Context, params model.ExportReportProcessMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishExportReportProcessMsg", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishExportReportProcessMsg indicates an expected call of PublishExportReportProcessMsg.
func (mr *MockMQMockRecorder) PublishExportReportProcessMsg(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishExportReportProcessMsg", reflect.TypeOf((*MockMQ)(nil).PublishExportReportProcessMsg), ctx, params)
}

// MockRedis is a mock of Redis interface.
type MockRedis struct {
	ctrl     *gomock.Controller
	recorder *MockRedisMockRecorder
	isgomock struct{}
}

// MockRedisMockRecorder is the mock recorder for MockRedis.
type MockRedisMockRecorder struct {
	mock *MockRedis
}

// NewMockRedis creates a new mock instance.
func NewMockRedis(ctrl *gomock.Controller) *MockRedis {
	mock := &MockRedis{ctrl: ctrl}
	mock.recorder = &MockRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedis) EXPECT() *MockRedisMockRecorder {
	return m.recorder
}

// LockExportReportProcess mocks base method.
func (m *MockRedis) LockExportReportProcess(ctx context.Context, params repository.LockExportReportProcess) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockExportReportProcess", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockExportReportProcess indicates an expected call of LockExportReportProcess.
func (mr *MockRedisMockRecorder) LockExportReportProcess(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockExportReportProcess", reflect.TypeOf((*MockRedis)(nil).LockExportReportProcess), ctx, params)
}

// LockExportReportRequest mocks base method.
func (m *MockRedis) LockExportReportRequest(ctx context.Context, params repository.LockExportReportRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockExportReportRequest", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockExportReportRequest indicates an expected call of LockExportReportRequest.
func (mr *MockRedisMockRecorder) LockExportReportRequest(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockExportReportRequest", reflect.TypeOf((*MockRedis)(nil).LockExportReportRequest), ctx, params)
}

// UnlockExportReportProcess mocks base method.
func (m *MockRedis) UnlockExportReportProcess(ctx context.Context, params repository.UnlockExportReportProcess) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockExportReportProcess", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockExportReportProcess indicates an expected call of UnlockExportReportProcess.
func (mr *MockRedisMockRecorder) UnlockExportReportProcess(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockExportReportProcess", reflect.TypeOf((*MockRedis)(nil).UnlockExportReportProcess), ctx, params)
}

// UnlockExportReportRequest mocks base method.
func (m *MockRedis) UnlockExportReportRequest(ctx context.Context, params repository.UnlockExportReportRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockExportReportRequest", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockExportReportRequest indicates an expected call of UnlockExportReportRequest.
func (mr *MockRedisMockRecorder) UnlockExportReportRequest(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockExportReportRequest", reflect.TypeOf((*MockRedis)(nil).UnlockExportReportRequest), ctx, params)
}

// MockS3 is a mock of S3 interface.
type MockS3 struct {
	ctrl     *gomock.Controller
	recorder *MockS3MockRecorder
	isgomock struct{}
}

// MockS3MockRecorder is the mock recorder for MockS3.
type MockS3MockRecorder struct {
	mock *MockS3
}

// NewMockS3 creates a new mock instance.
func NewMockS3(ctrl *gomock.Controller) *MockS3 {
	mock := &MockS3{ctrl: ctrl}
	mock.recorder = &MockS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3) EXPECT() *MockS3MockRecorder {
	return m.recorder
}

// GeneratePresignedDownloadURL mocks base method.
func (m *MockS3) GeneratePresignedDownloadURL(ctx context.Context, params repository.GeneratePresignedDownloadURLParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedDownloadURL", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedDownloadURL indicates an expected call of GeneratePresignedDownloadURL.
func (mr *MockS3MockRecorder) GeneratePresignedDownloadURL(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedDownloadURL", reflect.TypeOf((*MockS3)(nil).GeneratePresignedDownloadURL), ctx, params)
}

// UploadReportFile mocks base method.
func (m *MockS3) UploadReportFile(ctx context.Context, params repository.UploadReportFileParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadReportFile", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadReportFile indicates an expected call of UploadReportFile.
func (mr *MockS3MockRecorder) UploadReportFile(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadReportFile", reflect.TypeOf((*MockS3)(nil).UploadReportFile), ctx, params)
}
