// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fikrimohammad/go-dev-sdk/rocketmq/producer (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination sdk_rocketmq.go -package mocks -mock_names Client=MockProducerClient github.com/fikrimohammad/go-dev-sdk/rocketmq/producer Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	primitive "github.com/apache/rocketmq-client-go/v2/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockProducerClient is a mock of Client interface.
type MockProducerClient struct {
	ctrl     *gomock.Controller
	recorder *MockProducerClientMockRecorder
	isgomock struct{}
}

// MockProducerClientMockRecorder is the mock recorder for MockProducerClient.
type MockProducerClientMockRecorder struct {
	mock *MockProducerClient
}

// NewMockProducerClient creates a new mock instance.
func NewMockProducerClient(ctrl *gomock.Controller) *MockProducerClient {
	mock := &MockProducerClient{ctrl: ctrl}
	mock.recorder = &MockProducerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerClient) EXPECT() *MockProducerClientMockRecorder {
	return m.recorder
}

// PublishAsync mocks base method.
func (m *MockProducerClient) PublishAsync(ctx context.Context, topic, tag, key string, message []byte, callback func(context.Context, *primitive.SendResult, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAsync", ctx, topic, tag, key, message, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAsync indicates an expected call of PublishAsync.
func (mr *MockProducerClientMockRecorder) PublishAsync(ctx, topic, tag, key, message, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAsync", reflect.TypeOf((*MockProducerClient)(nil).PublishAsync), ctx, topic, tag, key, message, callback)
}

// PublishSync mocks base method.
func (m *MockProducerClient) PublishSync(ctx context.Context, topic, tag, key string, message []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSync", ctx, topic, tag, key, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSync indicates an expected call of PublishSync.
func (mr *MockProducerClientMockRecorder) PublishSync(ctx, topic, tag, key, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSync", reflect.TypeOf((*MockProducerClient)(nil).PublishSync), ctx, topic, tag, key, message)
}

// PublishSyncWithDelay mocks base method.
func (m *MockProducerClient) PublishSyncWithDelay(ctx context.Context, topic, tag, key string, message []byte, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSyncWithDelay", ctx, topic, tag, key, message, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSyncWithDelay indicates an expected call of PublishSyncWithDelay.
func (mr *MockProducerClientMockRecorder) PublishSyncWithDelay(ctx, topic, tag, key, message, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSyncWithDelay", reflect.TypeOf((*MockProducerClient)(nil).PublishSyncWithDelay), ctx, topic, tag, key, message, delay)
}
