// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fikrimohammad/go-dev-sdk/db (interfaces: DB)
//
// Generated by this command:
//
//	mockgen -destination sdk_db.go -package mocks github.com/fikrimohammad/go-dev-sdk/db DB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/fikrimohammad/go-dev-sdk/db"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (db.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(db.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}

// Close mocks base method.
func (m *MockDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDB)(nil).Close))
}

// NamedExecContext mocks base method.
func (m *MockDB) NamedExecContext(ctx context.Context, query string, arg any) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedExecContext", ctx, query, arg)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NamedExecContext indicates an expected call of NamedExecContext.
func (mr *MockDBMockRecorder) NamedExecContext(ctx, query, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedExecContext", reflect.TypeOf((*MockDB)(nil).NamedExecContext), ctx, query, arg)
}

// NamedGetContext mocks base method.
func (m *MockDB) NamedGetContext(ctx context.Context, dest any, query string, arg any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedGetContext", ctx, dest, query, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedGetContext indicates an expected call of NamedGetContext.
func (mr *MockDBMockRecorder) NamedGetContext(ctx, dest, query, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedGetContext", reflect.TypeOf((*MockDB)(nil).NamedGetContext), ctx, dest, query, arg)
}

// NamedSelectContext mocks base method.
func (m *MockDB) NamedSelectContext(ctx context.Context, dest any, query string, arg any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamedSelectContext", ctx, dest, query, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// NamedSelectContext indicates an expected call of NamedSelectContext.
func (mr *MockDBMockRecorder) NamedSelectContext(ctx, dest, query, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamedSelectContext", reflect.TypeOf((*MockDB)(nil).NamedSelectContext), ctx, dest, query, arg)
}
