// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fikrimohammad/efficient-report-exporter/internal/usecase (interfaces: Report)
//
// Generated by this command:
//
//	mockgen -destination internal/mock/report.go -package mock -mock_names Report=MockReportUseCase github.com/fikrimohammad/efficient-report-exporter/internal/usecase Report
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/fikrimohammad/efficient-report-exporter/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockReportUseCase is a mock of Report interface.
type MockReportUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReportUseCaseMockRecorder
	isgomock struct{}
}

// MockReportUseCaseMockRecorder is the mock recorder for MockReportUseCase.
type MockReportUseCaseMockRecorder struct {
	mock *MockReportUseCase
}

// NewMockReportUseCase creates a new mock instance.
func NewMockReportUseCase(ctrl *gomock.Controller) *MockReportUseCase {
	mock := &MockReportUseCase{ctrl: ctrl}
	mock.recorder = &MockReportUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportUseCase) EXPECT() *MockReportUseCaseMockRecorder {
	return m.recorder
}

// GetExportReportJob mocks base method.
func (m *MockReportUseCase) GetExportReportJob(ctx context.Context, params usecase.GetExportReportJobParams) (*usecase.GetExportReportJobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportReportJob", ctx, params)
	ret0, _ := ret[0].(*usecase.GetExportReportJobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportReportJob indicates an expected call of GetExportReportJob.
func (mr *MockReportUseCaseMockRecorder) GetExportReportJob(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportReportJob", reflect.TypeOf((*MockReportUseCase)(nil).GetExportReportJob), ctx, params)
}

// ListExportReportJobs mocks base method.
func (m *MockReportUseCase) ListExportReportJobs(ctx context.Context, params usecase.ListExportReportJobsParams) (*usecase.ListExportReportJobsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExportReportJobs", ctx, params)
	ret0, _ := ret[0].(*usecase.ListExportReportJobsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExportReportJobs indicates an expected call of ListExportReportJobs.
func (mr *MockReportUseCaseMockRecorder) ListExportReportJobs(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExportReportJobs", reflect.TypeOf((*MockReportUseCase)(nil).ListExportReportJobs), ctx, params)
}

// ProcessExportReport mocks base method.
func (m *MockReportUseCase) ProcessExportReport(ctx context.Context, params usecase.ProcessExportReportParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessExportReport", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessExportReport indicates an expected call of ProcessExportReport.
func (mr *MockReportUseCaseMockRecorder) ProcessExportReport(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessExportReport", reflect.TypeOf((*MockReportUseCase)(nil).ProcessExportReport), ctx, params)
}

// RequestExportReport mocks base method.
func (m *MockReportUseCase) RequestExportReport(ctx context.Context, params usecase.RequestExportReportParams) (*usecase.RequestExportReportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestExportReport", ctx, params)
	ret0, _ := ret[0].(*usecase.RequestExportReportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestExportReport indicates an expected call of RequestExportReport.
func (mr *MockReportUseCaseMockRecorder) RequestExportReport(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestExportReport", reflect.TypeOf((*MockReportUseCase)(nil).RequestExportReport), ctx, params)
}
