// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fikrimohammad/go-dev-sdk/s3 (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination internal/mock/sdk_s3.go -package mock -mock_names Client=MockS3Client github.com/fikrimohammad/go-dev-sdk/s3 Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	s3 "github.com/fikrimohammad/go-dev-sdk/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3Client is a mock of Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockS3Client) PresignGetObject(ctx context.Context, params s3.PresignGetObjectParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignGetObject", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockS3ClientMockRecorder) PresignGetObject(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockS3Client)(nil).PresignGetObject), ctx, params)
}

// UploadObject mocks base method.
func (m *MockS3Client) UploadObject(ctx context.Context, params s3.UploadObjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockS3ClientMockRecorder) UploadObject(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockS3Client)(nil).UploadObject), ctx, params)
}
